name: UI tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      allure_results_path: ${{ steps.upload-artifacts.outputs.artifact_path }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Playwright tests with pytest and generate Allure results
        run: |
          pytest -m regression --alluredir=allure-results --numprocesses 2

      - name: Upload allure-results artifact
        uses: actions/upload-artifact@v4
        id: upload-artifacts
        with:
          name: allure-results
          path: allure-results

  publish-report:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download Allure Results artifact
        uses: actions/download-artifact@v5
        with:
          name: allure-results
        id: download-artifacts

      - name: Download Allure History
        uses: actions/download-artifact@v3
        with:
          name: allure-history
          path: temp-history
        continue-on-error: true

      - name: Prepare allure-results with history
        run: |
          mkdir -p allure-results/history
          cp -r temp-history/* allure-results/history || echo "No history available"

      - name: Generate Allure Report with history
        uses: simple-elf/allure-report-action@v1.12
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history